export CATALINA_OPTS="$CATALINA_OPTS -Dspring.profiles.active=dev"
export CATALINA_OPTS="$CATALINA_OPTS -ea"
export CATALINA_OPTS="$CATALINA_OPTS -Daws.accessKeyId=AKIAJKQ7F2RQXROQWGBA"
export CATALINA_OPTS="$CATALINA_OPTS -Daws.secretKey=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"
export CATALINA_OPTS="$CATALINA_OPTS -Daws.region=us-east-1"