-- outdoorRecreation_id default null,
-- constraint fk_Image_Outdoor_Recreation
--     foreign key (outdoorRecreation_id)
--     references Outdoor_Recreations (id)
--     on delete no action
--     on update no action;